channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab
  - nb_conda_kernels
  - nodejs
  # Core R & tools
  - r-base=4.4
  - r-essentials
  - r-irkernel
  - r-languageserver
  - r-devtools
  # Plotting & data wrangling
  - r-tidyverse
  - r-ggplot2
  - r-plotly
  - r-data.table
  # (Optional) nice-to-haves
  - pandoc
  - quarto
  - tectonic
  - latexmk
